// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAprsbg3gZ6XJuIeVFCLDLBikvTvubiHM',
    appId: '1:366595905983:web:f1777ae75a167fd92e290a',
    messagingSenderId: '366595905983',
    projectId: 'fir-auth-db-storage',
    authDomain: 'fir-auth-db-storage.firebaseapp.com',
    storageBucket: 'fir-auth-db-storage.firebasestorage.app',
    measurementId: 'G-RSQX8SY1P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLoVEbDPHRjeCvHCf14gzbeqZm3S6v_g',
    appId: '1:366595905983:android:820496c8cb97e88e2e290a',
    messagingSenderId: '366595905983',
    projectId: 'fir-auth-db-storage',
    storageBucket: 'fir-auth-db-storage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-_7vKht84rlakzI3sN8KCFEY3lnawg5o',
    appId: '1:366595905983:ios:a5638be78c51ae1d2e290a',
    messagingSenderId: '366595905983',
    projectId: 'fir-auth-db-storage',
    storageBucket: 'fir-auth-db-storage.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDbStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-_7vKht84rlakzI3sN8KCFEY3lnawg5o',
    appId: '1:366595905983:ios:a5638be78c51ae1d2e290a',
    messagingSenderId: '366595905983',
    projectId: 'fir-auth-db-storage',
    storageBucket: 'fir-auth-db-storage.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDbStorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAprsbg3gZ6XJuIeVFCLDLBikvTvubiHM',
    appId: '1:366595905983:web:d433b0ae987afa872e290a',
    messagingSenderId: '366595905983',
    projectId: 'fir-auth-db-storage',
    authDomain: 'fir-auth-db-storage.firebaseapp.com',
    storageBucket: 'fir-auth-db-storage.firebasestorage.app',
    measurementId: 'G-RHTP6BK7GF',
  );
}
